(() => {
  'use strict';
  const BUILD = '20260723-v10-lite';
  const shops = [
    {id:101,name:'英雄商店',p:'A',currency:'金币 / 银币',items:'50类英雄碎片，248条配置',refresh:'每日6:00刷新',fact:'解锁“爱才”特权后，客户端说明为必出高级商品。典型碎片同轮第1份约为基础价10%，随后逐份上涨，到第10份接近基础价100%。',buy:['银币商品优先购买当前主将、助战或即将升星的英雄碎片','金币商品只补激活、升星或觉醒的关键缺口','每天6:00后查看一次即可，前几份低价档最划算'],avoid:'不要把金币分散给多名过渡英雄，也不要为了刷出某个英雄持续付费刷新。'},
    {id:102,name:'书商来访',p:'S',currency:'金币 / 银币',items:'43类技能，232条配置',refresh:'每日6:00刷新',fact:'解锁“传授”特权后，客户端说明为必出高级商品。典型技能同轮首份约20%基础价，后续逐步上涨，第10份可达到约200%基础价。',buy:['优先部署、大地颂歌、诱敌、高昂、战吼、火种之力、指挥','银币版本优先，金币版本只补核心技能等级节点','内政技能只给明确的资源队或产业英雄购买'],avoid:'不要机械清空10份；后半段单价明显更高，也不要购买与主力兵种不匹配的技能。'},
    {id:103,name:'竞技商城',p:'A',currency:'竞技币',items:'13类商品',refresh:'日重置；配置含3次刷新参数',fact:'刷新成本配置为10 / 20 / 30 / 40 / 50。商品包括美杜莎、雅典娜、海伦、辛西娅、盖亚碎片及四维属性、兵力类技能。',buy:['五名英雄只选当前阵容目标持续兑换','勇猛、渊博、气质、统率按主力英雄主属性选择','整顿、调配、强身、特训仅用于明确短板'],avoid:'不要四种属性技能平均换；目标未出现时也要控制刷新成本。'},
    {id:104,name:'王者商店',p:'S',currency:'英魂',items:'27类英雄碎片，54条配置',refresh:'日重置；配置含3次刷新参数',fact:'刷新成本参数为20。商品全部为英雄碎片，包括托尔、提尔、梅林、雅典娜、亚瑟、阿努比斯等。',buy:['锁定1名长期核心英雄持续兑换','接近激活、升星或觉醒节点时优先补齐','核心成型后再准备第二名英雄'],avoid:'不要同时兑换多名英雄，否则长期都无法形成有效星级。'},
    {id:105,name:'至臻商店',p:'B',currency:'金币',items:'35类商品，146条配置',refresh:'日重置；刷新成本20',fact:'单轮最大购买参数20。商品包括五类装备材料、精粹、兵种/职业文书、黄金加速道具及初中高级养成材料。',buy:['文书只买主力兵种或主力职业','装备材料与精粹只在打造、升阶卡点时补齐','高级稀缺材料优先于可日常获取的加速道具'],avoid:'不要因为“至臻”名称就清空商店；活动期购买应尽量叠加累计消费和限时免单。'},
    {id:106,name:'对决商店',p:'S',currency:'比武奖章',items:'39类战斗技能',refresh:'日重置；配置含3次刷新参数',fact:'刷新成本配置为10 / 20 / 30 / 40 / 50。包含兵种技能、主动技能及部署、指挥等辅助技能。',buy:['优先部署、大地颂歌、诱敌、高昂、战吼、火种之力、指挥','主动技能严格按英雄推荐表定向兑换','先升一套主队技能，再考虑第二队'],avoid:'不要按稀有度盲买，也不要因目标技能没出现而无限刷新。'},
    {id:107,name:'地精杂货铺',p:'B',currency:'银币 / 粮草 / 木材 / 黑铁',items:'10类道具，64条配置',refresh:'日重置；刷新成本5',fact:'单轮最大购买参数10。同类挖矿令、屯田令、伐木令、账本、募令、沙漏、科研令可使用不同基础资源购买。',buy:['主殿、研究或招兵卡时间时兑换对应加速道具','产业短缺时购买对应产业指令','优先消耗当前明显过剩的那一种基础资源'],avoid:'四种基础资源都紧缺时不要换；黄金道具只在活动冲刺或明确卡点使用。'},
    {id:108,name:'海盗市场',p:'A',currency:'失落古币',items:'26类商品',refresh:'日重置；刷新成本10',fact:'商品包含部署、指挥、勇猛、破甲、坚韧、火球、连射，以及元始天书、灵宝葫芦、太上敕令等宝物材料。',buy:['主队核心辅助技能和主动技能优先','部署、指挥等高频技能优先于泛用属性','宝物类只按当前已经确定的养成路线兑换'],avoid:'不要把失落古币平均换成多种低级技能，也不要投入无法近期成型的宝物半成品。'},
    {id:109,name:'要塞商店',p:'A',currency:'要塞硬币',items:'17类商品',refresh:'日重置；刷新成本10',fact:'包含四兵种技能锦囊、狂暴、部署、指挥、士气、军心、装备材料及部分坐骑/宝物碎片。',buy:['主力兵种技能锦囊优先','士气、军心等稀缺辅助技能按阵容需要兑换','装备材料在明确打造目标时补齐'],avoid:'不要四兵种锦囊同时买；坐骑或宝物碎片无法近期成型时先积币。'},
    {id:110,name:'赏金商店',p:'A',currency:'赏金',items:'6类商品，8条配置',refresh:'日重置配置，无手动刷新成本表',fact:'商品为急速行军、快速行军、账本、伐木令、屯田令、挖矿令，限量配置极高。',buy:['国战高频玩家优先行军道具','资源卡点时购买对应产业指令','根据当日攻城计划保留一部分赏金余额'],avoid:'非战斗期无需囤大量行军道具，也不要把所有赏金花在单一资源指令。'}
  ];
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const route=()=>{try{return decodeURIComponent(location.hash.slice(1)||'home')}catch{return location.hash.slice(1)||'home'}};

  function styles(){if($('#shopGuideStyles'))return;const s=document.createElement('style');s.id='shopGuideStyles';s.textContent=`
    .sg-head{position:relative;overflow:hidden;padding:24px;border:1px solid #bfd9e9;border-radius:12px;background:linear-gradient(135deg,#fff,#edf8ff 62%,#dceffd);box-shadow:0 10px 28px rgba(27,82,116,.08)}.sg-head:after{content:'SHOP';position:absolute;right:12px;top:-25px;font-size:96px;font-weight:900;color:rgba(19,126,190,.055)}.sg-head h1{position:relative;margin:8px 0;font-size:28px}.sg-head p{position:relative;max-width:820px;margin:0;color:#536b7c;line-height:1.8}.sg-badge{position:relative;display:inline-flex;padding:4px 9px;border:1px solid #bcdcf0;border-radius:999px;background:#e7f5ff;color:#126eaa;font-size:11px;font-weight:700}.sg-stats{position:relative;display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px;margin-top:17px}.sg-stat{padding:11px;border:1px solid #cfe2ee;border-radius:8px;background:rgba(255,255,255,.84);text-align:center}.sg-stat strong{display:block;color:#1178b8;font-size:20px}.sg-stat span{font-size:10px;color:#6c7d8b}
    .sg-insights{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:9px;margin:15px 0}.sg-insight{padding:14px;border:1px solid #d3e4ed;border-radius:9px;background:#fff}.sg-insight strong{display:block;color:#195f89;margin-bottom:6px}.sg-insight p{margin:0;color:#647987;font-size:11px;line-height:1.7}.sg-tabs{display:flex;flex-wrap:wrap;gap:7px;margin:14px 0}.sg-tab{padding:7px 11px;border:1px solid #c5dce9;border-radius:7px;background:#fff;color:#45657a;font-size:12px}.sg-tab.active,.sg-tab:hover{border-color:#168ed0;background:#168ed0;color:#fff}.sg-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:11px}.sg-card{padding:16px;border:1px solid #cbdde8;border-radius:10px;background:#fff;box-shadow:0 5px 16px rgba(24,75,105,.05)}.sg-card.hidden{display:none}.sg-top{display:flex;align-items:center;gap:7px;flex-wrap:wrap}.sg-chip{display:inline-flex;padding:3px 7px;border-radius:999px;background:#edf7fc;color:#267ba8;font-size:10px}.sg-priority{margin-left:auto;padding:3px 7px;border-radius:5px;background:#eaf8ef;color:#24824a;font-size:10px;font-weight:800}.sg-priority.b{background:#fff4dc;color:#986514}.sg-card h2{margin:10px 0 4px;font-size:18px}.sg-sub{margin:0 0 10px;color:#768a98;font-size:10px}.sg-card h3{margin:12px 0 6px;padding-bottom:5px;border-bottom:1px solid #e5edf2;font-size:13px}.sg-card ul{margin:0;padding-left:18px;color:#526b7b;font-size:12px;line-height:1.75}.sg-fact{margin-top:10px;padding:9px 11px;border-left:3px solid #3ca0d8;background:#f2faff;color:#446779;font-size:11px;line-height:1.7}.sg-avoid{margin-top:8px;padding:9px 11px;border-left:3px solid #d99b35;background:#fff9ec;color:#6c5a38;font-size:11px;line-height:1.7}.sg-table{margin-top:15px;padding:16px}.sg-table table{width:100%;border-collapse:collapse;font-size:12px}.sg-table th,.sg-table td{padding:10px;border-bottom:1px solid #e2ebf0;text-align:left;vertical-align:top}.sg-table th{background:#eef7fc;color:#3b6279}.sg-note{margin-top:14px;padding:13px 15px;border:1px solid #d2e1e9;border-radius:9px;background:#f8fcfe;color:#526b7b;font-size:11px;line-height:1.75}@media(max-width:940px){.sg-grid{grid-template-columns:1fr}.sg-insights{grid-template-columns:1fr 1fr}}@media(max-width:620px){.sg-head{padding:18px}.sg-head h1{font-size:23px}.sg-stats{grid-template-columns:repeat(2,1fr)}.sg-insights{grid-template-columns:1fr}.sg-table{overflow:auto}.sg-table table{min-width:650px}}
  `;document.head.appendChild(s)}

  function nav(){const left=$('#leftSidebar');if(left&&!left.querySelector('[data-shop-guide-link]')){const groups=$$('.side-group',left),g=groups.find(x=>x.querySelector('.side-group-title')?.textContent.includes('系统资料'))||groups[0];if(g){const a=document.createElement('a');a.className='side-link';a.href='#shop-guide';a.dataset.shopGuideLink='1';a.dataset.match='shop-guide';a.innerHTML='<span class="icon">▤</span>商店兑换<span class="count">10</span>';g.appendChild(a)}}const top=$('.top-links');if(top&&!top.querySelector('[data-shop-guide-top]')){const a=document.createElement('a');a.href='#shop-guide';a.dataset.shopGuideTop='1';a.textContent='商店攻略';top.appendChild(a)}}
  const card=s=>`<article class="sg-card" data-shop="${s.id}"><div class="sg-top"><span class="sg-chip">ID ${s.id}</span><span class="sg-chip">${esc(s.currency)}</span><span class="sg-priority ${s.p==='B'?'b':''}">常规优先级 ${s.p}</span></div><h2>${esc(s.name)}</h2><p class="sg-sub">${esc(s.items)} · ${esc(s.refresh)}</p><h3>${esc(s.name)}怎么换</h3><ul>${s.buy.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><div class="sg-fact"><strong>客户端配置：</strong>${esc(s.fact)}</div><div class="sg-avoid"><strong>避坑：</strong>${esc(s.avoid)}</div></article>`;

  function render(){const main=$('#mainContent');if(!main)return;main.innerHTML=`<header class="sg-head"><span class="sg-badge">Unity 2021.3.11f1 · APK cfg_shop</span><h1>商店兑换与刷新攻略</h1><p>从线上 APK 中解析出10类商店、848条商品配置，覆盖刷新成本、货币、限购和动态价格。攻略原则：专属货币集中培养一条路线，金币只解决确定性卡点。</p><div class="sg-stats"><div class="sg-stat"><strong>10</strong><span>商店类型</span></div><div class="sg-stat"><strong>848</strong><span>商品配置</span></div><div class="sg-stat"><strong>06:00</strong><span>英雄/书商刷新</span></div><div class="sg-stat"><strong>10—50</strong><span>常见刷新成本</span></div></div></header><section class="sg-insights"><article class="sg-insight"><strong>前几份价格更低</strong><p>英雄碎片典型曲线从基础价10%逐步升至100%；书商技能典型曲线从20%逐步升至200%。不要无脑买满。</p></article><article class="sg-insight"><strong>专属货币不要平均分</strong><p>英魂、竞技币、比武奖章、失落古币和要塞硬币，应围绕一名英雄或一套技能集中兑换。</p></article><article class="sg-insight"><strong>刷新也会消耗金币</strong><p>竞技、对决等商店设置了递增刷新成本。目标没有出现时，停手通常比继续刷更稳。</p></article></section><nav class="sg-tabs"><button class="sg-tab active" data-filter="0">全部</button>${shops.map(s=>`<button class="sg-tab" data-filter="${s.id}">${esc(s.name)}</button>`).join('')}</nav><div class="sg-grid">${shops.map(card).join('')}</div><section class="sg-table card"><h2>玩家路线速查</h2><table><thead><tr><th>玩家阶段</th><th>优先商店</th><th>核心目标</th><th>暂停条件</th></tr></thead><tbody><tr><td>开荒期</td><td>书商、英雄商店、地精杂货铺</td><td>主将碎片、核心技能、主殿与招兵卡点</td><td>金币不足或基础资源全面短缺</td></tr><tr><td>主队成型期</td><td>王者、对决、竞技</td><td>定向升星与一套高频技能</td><td>同时培养超过2名核心英雄</td></tr><tr><td>中后期</td><td>海盗、要塞、至臻</td><td>稀缺技能、宝物、装备材料与文书</td><td>无法形成完整路线或保底节点</td></tr><tr><td>国战活跃</td><td>赏金、地精杂货铺</td><td>行军效率和产业补给</td><td>非战斗期库存已经充足</td></tr></tbody></table></section><div class="sg-note"><strong>数据边界：</strong>APK 同时保留不同等级、品质和历史批次的商品配置。同名商品可能存在多组价格；当前角色实际看到的商品、折扣和剩余次数，以游戏内当次刷新为准。</div>`;$$('.sg-tab',main).forEach(b=>b.addEventListener('click',()=>{const id=Number(b.dataset.filter);$$('.sg-tab',main).forEach(x=>x.classList.toggle('active',x===b));$$('.sg-card',main).forEach(x=>x.classList.toggle('hidden',id&&Number(x.dataset.shop)!==id))}));if($('#rightSidebar'))$('#rightSidebar').innerHTML='<section class="right-card"><div class="right-card-title">商店速查</div><div class="right-card-body mini-links"><a href="#shop-guide">商店攻略</a><a href="#activity-guide">活动攻略</a><a href="#resources">资源规划</a><a href="#apk/catalog">道具目录</a></div></section><section class="right-card"><div class="right-card-title">核心提醒</div><div class="right-card-body"><p class="profile-desc">英雄商店、书商来访每日6:00刷新。</p><p class="profile-desc">同轮购买成本可能递增，优先买低价档。</p></div></section>';main.setAttribute('aria-busy','false');window.scrollTo({top:0,behavior:'auto'})}
  function handle(){styles();nav();if(route()==='shop-guide')setTimeout(render,0)}
  window.DGXS_SHOP_GUIDE={build:BUILD,shops};window.addEventListener('hashchange',handle);new MutationObserver(nav).observe(document.body,{childList:true,subtree:true});handle();
})();
